aliases: []
creation_timestamp: 1705230511857
current_stage: None
description: null
last_updated_timestamp: 1705230511857
name: best_xgboost
run_id: 5b276eeb82cd4d92bbf24d35b0f2e0b7
run_link: null
source: /home/ml-srv-admin/yet_another_mlops_project/mlflow/3/5b276eeb82cd4d92bbf24d35b0f2e0b7/artifacts/best_xgboost
status: READY
status_message: null
storage_location: /home/ml-srv-admin/yet_another_mlops_project/mlflow/3/5b276eeb82cd4d92bbf24d35b0f2e0b7/artifacts/best_xgboost
user_id: null
version: 4
