aliases: []
creation_timestamp: 1705241804822
current_stage: None
description: null
last_updated_timestamp: 1705241804822
name: best_transf_xgboost
run_id: 43aa6b4078c647a58459753eccdc298f
run_link: null
source: /home/ml-srv-admin/yet_another_mlops_project/mlflow/8/43aa6b4078c647a58459753eccdc298f/artifacts/best_transf_xgboost
status: READY
status_message: null
storage_location: /home/ml-srv-admin/yet_another_mlops_project/mlflow/8/43aa6b4078c647a58459753eccdc298f/artifacts/best_transf_xgboost
user_id: null
version: 2
