channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - numpy==1.26.3
  - pandas==2.1.4
  - scikit-learn==1.3.2
  - scipy==1.11.4
  - xgboost==2.0.3
name: mlflow-env
